language: python
python:
  - 2.6
  - 2.7
env:
  - DJANGO=1.3.1
install:
  - pip install -r requirements.txt --use-mirrors
  - pip install -r requirements-test.txt --use-mirrors
before_script:
  - cp scielomanager/settings_local.include-TEMPLATE scielomanager/settings_local.include
script:
  - make test
