language: python
python:
  - 2.6
  - 2.7
env:
  - DJANGO=1.3.1
install:
  - pip install -r requirements.txt --use-mirrors
before_script:
  - psql -c 'create database journalmanager;' -U postgres
  - cp scielomanager/settings_local.include-TEMPLATE scielomanager/settings_local.include
script:
  - make test
postgres:
  adapter: postgresql
  database: journalmanager
  username: postgres
